#! /bin/sh

sxhkd &

$HOME/.config/polybar/launchbspwm.sh &
feh --bg-scale /home/soapman/Images/wadarth.jpg &
pulseaudio &
compton --shadow-exclude-reg 1366x25+0+0 --respect-prop-shadow -cfG &
udiskie &
setxkbmap -layout us,ru -option 'grp:caps_toggle' &
thunar --daemon &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config single_monocle true
bspc config presel_feedback_color "#353535"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a Transmission-gtk desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Fceux state=pseudo_tiled rectangle=760x700+0+0
#bspc rule -a URxvt:dropdown state=floating rectangle=640x400+363+198
#urxvt -name 'dropdown' &
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on rectangle=640x400+363+198
urxvt -name scratchpad -e ~/.config/bspwm/scratch &

